// Portfolio applications are original teaching prompts, not diagnoses or fixed style rules.
export const archetypes = [
  {
    name: "Innocent",
    motive: "Optimism",
    voice: "Clear, hopeful, sincere",
    promise: "Make everyday things feel simpler.",
    evidence: "Show a project that removes an unnecessary complication.",
    risk: "Oversimplifying a difficult problem",
    direction: "Open space, gentle rhythm, direct language",
  },
  {
    name: "Explorer",
    motive: "Freedom",
    voice: "Curious, independent, open",
    promise: "Find possibilities beyond the familiar.",
    evidence: "Document an experiment and what surprised you.",
    risk: "Novelty without a clear purpose",
    direction: "Open compositions, exploratory imagery, field notes",
  },
  {
    name: "Sage",
    motive: "Understanding",
    voice: "Thoughtful, precise, explanatory",
    promise: "Make complex ideas understandable.",
    evidence: "Publish research, sources, and the reasoning behind decisions.",
    risk: "Expert language that excludes readers",
    direction: "Editorial hierarchy, annotations, legible charts",
  },
  {
    name: "Hero",
    motive: "Mastery",
    voice: "Determined, direct, encouraging",
    promise: "Meet the challenge with skill and effort.",
    evidence:
      "Show a difficult constraint and the work you did to overcome it.",
    risk: "Overclaiming individual credit",
    direction: "Strong hierarchy, confident type, visible outcomes",
  },
  {
    name: "Outlaw",
    motive: "Change",
    voice: "Challenging, candid, independent",
    promise: "Question the convention that is holding us back.",
    evidence: "Explain a rule you challenged and why the alternative worked.",
    risk: "Rebellion that makes the experience harder to use",
    direction: "Deliberate disruption, bold contrast, sharp copy",
  },
  {
    name: "Magician",
    motive: "Transformation",
    voice: "Imaginative, compelling, visionary",
    promise: "Turn a possibility into a new experience.",
    evidence:
      "Pair a working transformation with an explanation of how it works.",
    risk: "Mystique replacing honest explanation",
    direction: "Reveals, unexpected connections, focused visual moments",
  },
  {
    name: "Everyperson",
    motive: "Belonging",
    voice: "Approachable, practical, conversational",
    promise: "Make useful things for people like us.",
    evidence: "Show collaboration and the ordinary needs behind the brief.",
    risk: "Becoming so generic that your contribution disappears",
    direction: "Familiar patterns, warm copy, inclusive imagery",
  },
  {
    name: "Lover",
    motive: "Connection",
    voice: "Attentive, expressive, appreciative",
    promise: "Make the experience feel considered.",
    evidence: "Explain details that help people feel understood.",
    risk: "Surface beauty without substance",
    direction: "Careful typography, rich detail, intentional pacing",
  },
  {
    name: "Jester",
    motive: "Enjoyment",
    voice: "Playful, witty, spontaneous",
    promise: "Bring a little delight to the task.",
    evidence:
      "Show a playful interaction that still helps someone finish their task.",
    risk: "Humor that distracts or excludes",
    direction: "Unexpected copy, lively accents, optional motion",
  },
  {
    name: "Caregiver",
    motive: "Care",
    voice: "Supportive, patient, reassuring",
    promise: "Help people feel supported.",
    evidence: "Document accessibility decisions and helpful error recovery.",
    risk: "Speaking for users instead of listening to them",
    direction: "Readable type, calm pacing, helpful guidance",
  },
  {
    name: "Creator",
    motive: "Expression",
    voice: "Inventive, thoughtful, expressive",
    promise: "Make something worth bringing into the world.",
    evidence: "Share sketches, iterations, and the finished craft.",
    risk: "Perfectionism that hides unfinished learning",
    direction: "Distinct compositions, process imagery, crafted details",
  },
  {
    name: "Ruler",
    motive: "Order",
    voice: "Composed, responsible, decisive",
    promise: "Create a system people can rely on.",
    evidence: "Show consistent components, documentation, and clear ownership.",
    risk: "An authoritative voice that feels inflexible",
    direction: "Stable grids, restrained palette, systematic spacing",
  },
];
